{
 "title": "slice_c6ac6d56_baff_4d1f_9b71_c40deb132d00",
 "tags": [ "slice" ],
 "time": { "from": "2025-03-10T10:20:49.319Z", "to": "2025-03-10T10:21:13.043Z" },
 "panels": [
  {
   "title": "Network Service Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ns_status{instance=\"katana-nfv_mon:8002\"}"
    }
   ]
  },
  {
   "title": "Active VMs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (status) (openstack_nova_server_status)\n\n"
    }
   ]
  },
  {
   "title": "vm_memory_actual",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\"})\n"
    }
   ]
  },
  {
   "title": "Total Vcpus",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_limits_vcpus_max)"
    }
   ]
  },
  {
   "title": "vm_memory_available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\"})\n"
    }
   ]
  },
  {
   "title": "vm_cpu_overall_cpu_usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_limits_vcpus_used)"
    }
   ]
  },
  {
   "title": "vm_memory_usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openstack_nova_limits_memory_used{tenant=\"vim_0_katana_c6ac6d56-baff-4d1f-9b71-c40deb132d00\"}\n"
    }
   ]
  },
  {
   "title": "Availelable Storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "120-openstack_nova_server_local_gb{tenant_id=\"94fea73dcbb64de88af1a41461cc82e9\"}",
     "legendFormat": "GB"
    }
   ]
  },
  {
   "title": "Used Storage From Vms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_nova_server_local_gb)"
    }
   ]
  }
 ]
}